# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2015-2016.

branches:
  only:
    - develop

git:
  depth: 1

dist: trusty

language: c

compiler:
  - gcc

env:
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    - env: TESTING_REPORTS=1

before_script:
  - mkdir -p "${TRAVIS_BUILD_DIR}/../testing-reports"

script:
  - cd "${TRAVIS_BUILD_DIR}/../testing-reports"
  - "${TRAVIS_BUILD_DIR}/reports/src/build_results_all.sh"

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/../testing-reports
